apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-abacate
  labels:
    app: chatbot-abacate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot-abacate
  template:
    metadata:
      labels:
        app: chatbot-abacate
    spec:
      containers:
      - name: chatbot-abacate
        image: nerton/chatbot-abacate
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_HOST
          value: "mysql"
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_NAME
          value: "abacate"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
