apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  # Troque estes valores para algo seguro ou crie o secret com kubectl create secret
  mysql-root-password: rootpassword
  mysql-user: abacate
  mysql-password: abacatepass
